#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Error: please run as root!"
  exit 1
fi

for var in "$@"
do
    if [[ "$found" == true ]]; then
        CONFIG_FILE="$var"
        # echo "true $CONFIG_FILE"
        break
    fi
    if [[ "$var" == "--config" ]]; then
        found=true
    fi
done

regex="^server\s+(.*)\s+(.*)"
while IFS= read -r line
do
    # echo $line
    if [[ "$line" =~ $regex ]]
    then
        TUNNEL_ADDRESS="${BASH_REMATCH[1]}"
        TUNNEL_NETMASK="${BASH_REMATCH[2]}"
        echo "ip ${TUNNEL_ADDRESS}"
        echo "nm ${TUNNEL_NETMASK}"
    fi
done < "$CONFIG_FILE"

iptables -t nat -A POSTROUTING -s $TUNNEL_ADDRESS/$TUNNEL_NETMASK -j MASQUERADE -m comment --comment "generated by easy-openvpn-server"

ORIG_FORWARD_VALUE=$(sysctl net.ipv4.ip_forward -b)
sysctl -w net.ipv4.ip_forward=1

function cleanup {
  echo Cleaning up...
  sysctl -w net.ipv4.ip_forward=${ORIG_FORWARD_VALUE}
  iptables -t nat -D POSTROUTING -s $TUNNEL_ADDRESS/$TUNNEL_NETMASK -j MASQUERADE -m comment --comment "generated by easy-openvpn-server"
}
trap cleanup EXIT

# Execute normally instead of with exec so our trap works correctly.
$@
