#!/bin/bash
set -e

source $SNAP_USER_DATA/init.sh

iptables -t nat -A POSTROUTING -s $OVPN_NETWORK -j MASQUERADE -m comment --comment "/* generated by easy-openvpn-server */"

ORIG_FORWARD_VALUE=$(sysctl net.ipv4.ip_forward -b)
sysctl -w net.ipv4.ip_forward=1

function cleanup {
  echo Cleaning up...
  sysctl -w net.ipv4.ip_forward=${ORIG_FORWARD_VALUE}
  iptables -t nat -D POSTROUTING -s $OVPN_NETWORK -j MASQUERADE -m comment --comment "/* generated by easy-openvpn-server */"
}
trap cleanup EXIT

$@
